name: Check formatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install
      - name: Format files
        run: npm run precommit
      - name: Check diff
        run: |
          git diff
          test -z "$(git status -s)"
